import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Memo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      {/* Warning: Extra attributes from the server: class,style のエラー回避 */}
      <html lang="ja" suppressHydrationWarning>
        <body className={inter.className}>
          <Providers>
            {/*  */}
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
